import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const sampleHotels = [
  {
    hotelName: 'Grand Palace Resort Goa',
    hotelCode: 'HTL-1001',
    hotelCategory: '5 Star',
    description: 'Experience luxury at its finest with our beachfront resort featuring world-class amenities.',
    email: 'info@grandpalacegoa.com',
    phoneNumber: '9876543210',
    country: 'India',
    state: 'Goa',
    city: 'Goa',
    area: 'Baga Beach',
    landmark: 'Near Tito\'s Lane',
    pincode: '403516',
    latitude: 15.5553,
    longitude: 73.7517,
    totalFloors: 5,
    hasSwimmingPool: true,
    hasSpa: true,
    hasGym: true,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.8,
    totalReviews: 1250,
  },
  {
    hotelName: 'Ocean View Retreat',
    hotelCode: 'HTL-1002',
    hotelCategory: '4 Star',
    description: 'A serene getaway offering breathtaking ocean views and modern comforts.',
    email: 'hello@oceanviewgoa.com',
    phoneNumber: '9876543211',
    country: 'India',
    state: 'Goa',
    city: 'Goa',
    area: 'Calangute',
    landmark: 'Opposite Calangute Beach',
    pincode: '403516',
    latitude: 15.5494,
    longitude: 73.7554,
    totalFloors: 4,
    hasSwimmingPool: true,
    hasSpa: false,
    hasGym: true,
    hasParking: true,
    hasAirportPickup: false,
    hasFreeWiFi: true,
    hasPetFriendly: true,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: false,
    coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.5,
    totalReviews: 850,
  },
  {
    hotelName: 'Sunset Beach Resort',
    hotelCode: 'HTL-1003',
    hotelCategory: 'Resort',
    description: 'Perfect family destination with direct beach access and multiple pools.',
    email: 'bookings@sunsetresort.com',
    phoneNumber: '9876543212',
    country: 'India',
    state: 'Goa',
    city: 'Goa',
    area: 'Candolim',
    landmark: 'Fort Aguada Road',
    pincode: '403515',
    latitude: 15.5186,
    longitude: 73.7634,
    totalFloors: 3,
    hasSwimmingPool: true,
    hasSpa: true,
    hasGym: false,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.6,
    totalReviews: 920,
  },
  {
    hotelName: 'Royal Heritage Hotel',
    hotelCode: 'HTL-1004',
    hotelCategory: 'Boutique',
    description: 'Experience the royal charm in the heart of the city.',
    email: 'stay@royalheritage.com',
    phoneNumber: '9876543213',
    country: 'India',
    state: 'Goa',
    city: 'Goa',
    area: 'Panaji',
    landmark: 'Near Church Square',
    pincode: '403001',
    latitude: 15.4989,
    longitude: 73.8278,
    totalFloors: 4,
    hasSwimmingPool: false,
    hasSpa: false,
    hasGym: true,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1542314831-c6a4d27df08f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.3,
    totalReviews: 450,
  },
  {
    hotelName: 'Mumbai Skyline Towers',
    hotelCode: 'HTL-1005',
    hotelCategory: '5 Star',
    description: 'Ultra-modern business hotel with stunning skyline views.',
    email: 'mumbai@skylinetowers.com',
    phoneNumber: '9876543214',
    country: 'India',
    state: 'Maharashtra',
    city: 'Mumbai',
    area: 'Bandra Kurla Complex',
    landmark: 'BKC Financial District',
    pincode: '400051',
    latitude: 19.0658,
    longitude: 72.8661,
    totalFloors: 25,
    hasSwimmingPool: true,
    hasSpa: true,
    hasGym: true,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.9,
    totalReviews: 3200,
  },
  {
    hotelName: 'Marine Drive Boutique',
    hotelCode: 'HTL-1006',
    hotelCategory: 'Boutique',
    description: 'Charming sea-facing rooms on the iconic Marine Drive.',
    email: 'stay@marinedriveboutique.com',
    phoneNumber: '9876543215',
    country: 'India',
    state: 'Maharashtra',
    city: 'Mumbai',
    area: 'Marine Drive',
    landmark: 'Opposite Queen\'s Necklace',
    pincode: '400020',
    latitude: 18.9415,
    longitude: 72.8236,
    totalFloors: 6,
    hasSwimmingPool: false,
    hasSpa: false,
    hasGym: false,
    hasParking: false,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: false,
    hasConferenceHall: false,
    coverImage: 'https://images.unsplash.com/photo-1551882547-ff40eb0d1b73?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.7,
    totalReviews: 890,
  },
  {
    hotelName: 'Delhi Capital Suites',
    hotelCode: 'HTL-1007',
    hotelCategory: '4 Star',
    description: 'Comfortable suites perfectly suited for business travelers in New Delhi.',
    email: 'info@delhicapital.com',
    phoneNumber: '9876543216',
    country: 'India',
    state: 'Delhi',
    city: 'New Delhi',
    area: 'Connaught Place',
    landmark: 'Inner Circle',
    pincode: '110001',
    latitude: 28.6304,
    longitude: 77.2177,
    totalFloors: 8,
    hasSwimmingPool: false,
    hasSpa: false,
    hasGym: true,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1596436889106-be35e843f974?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.4,
    totalReviews: 670,
  },
  {
    hotelName: 'Bangalore Tech Park Hotel',
    hotelCode: 'HTL-1008',
    hotelCategory: '4 Star',
    description: 'Located adjacent to major IT parks, ideal for short business stays.',
    email: 'blr@techparkhotel.com',
    phoneNumber: '9876543217',
    country: 'India',
    state: 'Karnataka',
    city: 'Bangalore',
    area: 'Whitefield',
    landmark: 'Next to ITPL',
    pincode: '560066',
    latitude: 12.9850,
    longitude: 77.7360,
    totalFloors: 10,
    hasSwimmingPool: true,
    hasSpa: true,
    hasGym: true,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.6,
    totalReviews: 1100,
  },
  {
    hotelName: 'Jaipur Palace Residency',
    hotelCode: 'HTL-1009',
    hotelCategory: '5 Star',
    description: 'Live like royalty in this magnificent heritage property.',
    email: 'royal@jaipurpalace.com',
    phoneNumber: '9876543218',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    area: 'Rambagh',
    landmark: 'Near Albert Hall Museum',
    pincode: '302004',
    latitude: 26.8988,
    longitude: 75.8055,
    totalFloors: 3,
    hasSwimmingPool: true,
    hasSpa: true,
    hasGym: false,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: true,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1585808740177-33a8b419ce6a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.9,
    totalReviews: 2400,
  },
  {
    hotelName: 'Hyderabad Pearl Hotel',
    hotelCode: 'HTL-1010',
    hotelCategory: '5 Star',
    description: 'Luxury accommodations with exquisite dining options in the City of Pearls.',
    email: 'stay@hydpearl.com',
    phoneNumber: '9876543219',
    country: 'India',
    state: 'Telangana',
    city: 'Hyderabad',
    area: 'Banjara Hills',
    landmark: 'Road No 12',
    pincode: '500034',
    latitude: 17.4156,
    longitude: 78.4347,
    totalFloors: 12,
    hasSwimmingPool: true,
    hasSpa: true,
    hasGym: true,
    hasParking: true,
    hasAirportPickup: true,
    hasFreeWiFi: true,
    hasPetFriendly: false,
    hasRoomService: true,
    hasBar: true,
    hasConferenceHall: true,
    coverImage: 'https://images.unsplash.com/photo-1549294413-26f195200c16?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    hotelRating: 4.7,
    totalReviews: 1800,
  }
];

async function main() {
  console.log('Seeding MasterHotelCategory database...');
  const categories = ['3 Star', '4 Star', '5 Star', 'Resort', 'Boutique', 'Heritage'];
  for (const cat of categories) {
    await prisma.masterHotelCategory.upsert({
      where: { name: cat },
      update: {},
      create: { name: cat },
    });
  }

  const existing = await prisma.masterHotel.count();
  if (existing > 0) {
    console.log(`Database already contains ${existing} hotels. Seeding skipped.`);
    return;
  }

  console.log('Seeding MasterHotel database with 10 detailed samples...');

  for (const h of sampleHotels) {
    const hotel = await prisma.masterHotel.create({
      data: {
        ...h,
        totalRooms: 60, // we'll create room types that sum to this
        totalRoomTypes: 3,
        totalRestaurants: 2
      }
    });

    // Create Room Types
    await prisma.masterRoomType.createMany({
      data: [
        {
          hotelId: hotel.id,
          roomTypeName: 'Deluxe Room',
          roomTypeCode: 'DLX',
          numberOfRooms: 30,
          maxOccupancy: 2,
          basePrice: 5500,
          bedType: 'King',
          roomSize: '350 sq ft',
          amenities: 'AC, TV, Minibar'
        },
        {
          hotelId: hotel.id,
          roomTypeName: 'Executive Room',
          roomTypeCode: 'EXE',
          numberOfRooms: 20,
          maxOccupancy: 2,
          basePrice: 7500,
          bedType: 'King',
          roomSize: '450 sq ft',
          amenities: 'AC, TV, Minibar, City View'
        },
        {
          hotelId: hotel.id,
          roomTypeName: 'Suite',
          roomTypeCode: 'STE',
          numberOfRooms: 10,
          maxOccupancy: 4,
          basePrice: 12000,
          bedType: 'King + Sofa Bed',
          roomSize: '650 sq ft',
          amenities: 'AC, TV, Minibar, Ocean View, Bathtub'
        }
      ]
    });

    // Create Restaurants
    await prisma.masterRestaurant.createMany({
      data: [
        {
          hotelId: hotel.id,
          restaurantName: `${hotel.hotelName} Signature Dining`,
          restaurantType: 'Fine Dining',
          cuisine: 'Multi-Cuisine',
          foodType: 'Veg & Non-Veg',
          seatingCapacity: 80,
          openingTime: '07:00 AM',
          closingTime: '11:00 PM',
        },
        {
          hotelId: hotel.id,
          restaurantName: `Pure Bliss Cafe`,
          restaurantType: 'Cafe',
          cuisine: 'Continental',
          foodType: 'Veg Only',
          seatingCapacity: 40,
          openingTime: '09:00 AM',
          closingTime: '08:00 PM',
        }
      ]
    });
  }

  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
